spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gomez123.
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
      strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.PostgreSQL94Dialect

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8099/eureka