spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gomez123.
    driver-class-name: org.postgresql.Driver
    application:
      name: plazoleta-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

